name: Build and Deploy AMP site
on:
  push:
    branches: ["main"] # или "master"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Generate AMP copies
        run: |
          # Создаем базовую папку
          mkdir -p amp

          # Список ваших коллекций
          collections=("_toponymy" "_mysteries-dolmens" "_info")

          for coll in "${collections[@]}"; do
            # Проверяем, существует ли папка коллекции
            if [ -d "$coll" ]; then
              # Определяем целевую папку без подчеркивания (например, amp/toponymy)
              folder_name="${coll#_}"
              mkdir -p "amp/$folder_name"
              
              # Обрабатываем файлы коллекции
              for f in "$coll"/*.md; do
                [ -e "$f" ] || continue
                
                # Имя файла
                filename="${f##*/}"
                
                # Меняем layout и сохраняем в amp/имя_коллекции/файл.md
                sed 's/^layout: .*/layout: amp/' "$f" > "amp/$folder_name/$filename"
              done
            fi
          done
      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
